### ISSUE TITLE
How to remove document<>

### ISSUE THREAD

**Issue by kot10n5tn** [1amageek/Ballcap-iOS#10]
![image](https://user-images.githubusercontent.com/40314657/57598517-880efc00-758e-11e9-9d66-a2a32291bedb.png)

``` swift
print(Document<User>.modelName) // user
```

I'm a Pring user. I appreciate it.

ModelName is `user`, but collection name is `document<user>`. In case of Pring, collection name is `user`. Is this a Ballcap's feature? Can I change collection name without overriding `Document` class?

**Comment by 1amageek** [comment]
Thank you for your message.

Please provide the version you are using and the code needed to reproduce it.

**Comment by kot10n5tn** [comment]
Thank you.

Ballcap version: 0.5.11

``` Swift
import Ballcap

struct User: Codable, Equatable, Modelable {
    
    var name: String = ""
    var imageURL: String?
    
}
```

``` Swift
Auth.auth().signIn(
            withEmail: email,
            password: password) { (result, error) in
                guard let uid = result?.user.uid else {
                    return
                }
                
                var user = Document<User>(id: uid)
                user.data?.imageURL = "imageURL"
                user.data?.name = "name"
                user.save()
        }
```

**Comment by 1amageek** [comment]
I recommend using the latest version.
https://github.com/1amageek/Ballcap-iOS/releases

`modelName` has already been removed. There is a contradiction with the test result of Ballcap.
https://github.com/1amageek/Ballcap-iOS/blob/master/BallcapTests/DocumentTests.swift#L23

Check the result of the following code:
```swift
print(user.documentReference)
```

**Comment by kot10n5tn** [comment]
I have updated Ballcap v0.6.2, but `document<>` remains. I try to find the reason.

``` Swift
print(user.documentReference.path)
// document<user>/YyYNlpj94NgTY1pjQfyq5fwddoA3
```

**Comment by 1amageek** [comment]
This issue can not be reproduced.

<img width="356" alt="スクリーンショット 2019-05-17 11 18 52" src="https://user-images.githubusercontent.com/11146538/57898842-aaa65b00-7895-11e9-8a12-7c48aca0af6f.png">

```swift
version/1/user/a
```


It may be related to `Auth`. `Auth` contains` User` class. You may need to give your `User` class a namespace.

**Comment by undoroid** [comment]
I have the same problem. There seems to be a problem with the logic to get the name of the type.
- code
![image](https://user-images.githubusercontent.com/3245867/58159885-5bf32980-7cb8-11e9-9740-544bf823bfef.png)

- log
![image](https://user-images.githubusercontent.com/3245867/58159949-762d0780-7cb8-11e9-8334-708ad0abef58.png)

**Comment by 1amageek** [comment]
@undoroid @kot10n5tn Thank you. I reproduced it in my environment.
