### ISSUE TITLE
FR: DataSource support BindableObject

### ISSUE THREAD

**Issue by 1amageek** [1amageek/Ballcap-iOS#12]
Consider correspondence of BindableObject in order to correspond to SwiftUI seamlessly

https://developer.apple.com/documentation/swiftui/bindableobject

**Comment by kinergy** [comment]
https://developer.apple.com/documentation/combine/observableobject

any plans on implementing this?

**Comment by 1amageek** [comment]
https://github.com/1amageek/Ballcap-iOS/blob/master/examples/WithSwiftUI/WithSwiftUI/Models/User.swift
