### ISSUE TITLE
configure is inaccessible

### ISSUE THREAD

**Issue by priore** [1amageek/Ballcap-iOS#14]
### Describe the bug
BallcapApp.configure showing the message  "inaccessible due to internal protection level message".

### [REQUIRED] Step 1: Describe your environment

  * Xcode version: 10.2.1
  * Bellcap version: 0.6.0

#### Steps to reproduce:

Put `BallcapApp.configure` in a class and after try to compile.

#### Relevant Code:

```swift
BallcapApp.configure(Firestore.firestore().document("version/1"))
```

**Comment by 1amageek** [comment]
Hi. 
Thank your for your message.

Use the latest version of Ballcap.

https://github.com/1amageek/Ballcap-iOS/releases
