### ISSUE TITLE
Object' does not conform to protocol 'Modelable'

### ISSUE THREAD

**Issue by SebastianBO** [1amageek/Ballcap-iOS#20]
### [REQUIRED] Step 1: Describe your environment

  * Xcode version: _____
  * Pring version: _____

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by 1amageek** [comment]
@SebastianBO You need to explain the detailed situation.

**Comment by SebastianBO** [comment]
Sorry,
Latest Xcode/Pring version.

The model is "Modelable" and yet I get the error, Object' does not conform to protocol 'Modelable'.
Tried a lot of various solutions, what am I missing? 
Thanks for the great work.
1. Get documents
```
let document: Document<Model> = Document("DOCUMENT_ID")
document.get { (document, error) in
   print(document.data)
}
```
2. Collection Reference
``
let query: DataSource<Document<Item>>.Query = DataSource.Query(Firestore.firestore().collectionGroup("items"))
let dataSource = DataSource(reference: query)
``

**Comment by 1amageek** [comment]
Thank you for using Pring.
In this library, Document and Model are separated.

`Modelable` is a Protocol for defining a Model.
`Object` has Model as a property.

https://github.com/1amageek/Ballcap-iOS#scheme

---

Any struct that conforms to `Modelable & Codable` can be handled by` Document <Model> `.
`Document` is a class created by inheriting` Object`.

**Comment by SebastianBO** [comment]
Been trying to solve this over the weekend, with your updated scheme and instructions. It would be nice with a working example of subcollections and retrieve a specific document

**Comment by 1amageek** [comment]
@SebastianBO 
```swift
let documentReference: DocumentReference = firestore.document("YOUR_PATH")
let doc: Document<Model> = Document(documentReference)
```
```swift
Document<Model>.get(documentReference: documentReference) { document, error

}
```

**Comment by SebastianBO** [comment]
Even more confusing

**Comment by 1amageek** [comment]
@SebastianBO 
I don't know what you want to understand.
You need to prepare sample code and a reproducible environment.

## Use Document

```swift
let documentReference: DocumentReference = firestore.document("YOUR_PATH")
let doc: Document<Model> = Document(documentReference)
```
```swift
Document<Model>.get(documentReference: documentReference) { document, error

}
```

## Use Class that inherits Object

```swift
let documentReference: DocumentReference = firestore.document("YOUR_PATH")
let user: User = User(documentReference)
```
```swift
// get from document ref
User.get(documentReference: documentReference) { user, error

}

// get from document id
User.get(id: "USER_ID") { user, error

}
```

**Comment by SebastianBO** [comment]
Agree, sorry.

1. Sub Collection as DataSource - not getting it to work in SwiftUI
2. Retrieve specific document from DB (User) guess it's answered above
3. Create/Save a document with a specific ID.

Where can I donate to this project?

**Comment by 1amageek** [comment]
@SebastianBO 
Can you publish part of your code with gist? It would be better for me to see it.

**Comment by 1amageek** [comment]
@SebastianBO 

> Sub Collection as DataSource - not getting it to work in SwiftUI
https://github.com/1amageek/Ballcap-iOS/blob/master/README.md#your-custom-object

> Create/Save a document with a specific ID.
https://github.com/1amageek/Ballcap-iOS/blob/master/README.md#initialization

**Comment by SebastianBO** [comment]
Thank you a lot, very appreciated! I'll come back with results if interested

**Comment by SebastianBO** [comment]
``       let uid = Auth.auth().currentUser!.uid
                let document: Document<User.Model> = Document(id: uid)
                document.save()
``
This saves it to "document<model> collection"
and not ``     override class var name: String { "users" } collection
``

**Comment by SebastianBO** [comment]
<img width="306" alt="Screenshot 2019-12-12 at 14 44 53" src="https://user-images.githubusercontent.com/1634003/70717099-f61acd80-1ced-11ea-90ea-8c2fd9ac2367.png">

**Comment by 1amageek** [comment]
@SebastianBO What version are you using?
If it's happening in the latest version, it's a bug, so please describe the code that can be reproduced with a new issue.

I need to fix it.

**Comment by SebastianBO** [comment]
It's the latest version. 
Just create a document with a specific ID gives this results.

**Comment by 1amageek** [comment]
@SebastianBO 

Thank you.

I'm testing, but that doesn't happen.
Publish a repository that can be reproduced.

https://github.com/1amageek/Ballcap-iOS/blob/master/BallcapTests/DocumentTests.swift#L61
https://github.com/1amageek/Ballcap-iOS/blob/master/BallcapTests/DocumentTests.swift#L201

![スクリーンショット 2019-12-18 16 19 13](https://user-images.githubusercontent.com/11146538/71064329-34aefd00-21b2-11ea-82ad-fc96fa95119b.png)
