### ISSUE TITLE
Consider adding to firebaseopensource.com

### ISSUE THREAD

**Issue by thatfiredev** [1amageek/Ballcap-iOS#28]
This is a great project and it's surely helpful for Firebase Developers. Consider [adding](https://github.com/firebase/firebaseopensource.com/issues/new?template=new_project.md) it to [firebaseopensource.com](https://firebaseopensource.com).

See [configuring your repo](https://github.com/firebase/firebaseopensource.com/blob/master/docs/configure-repo.md) for additional instructions.

**Comment by 1amageek** [comment]
@rosariopfernandes Hi!　
Thanks for the great suggestions.
The work is done. I'm looking forward to getting a lot of people to use this project.

https://github.com/firebase/firebaseopensource.com/pull/182
